### ISSUE TITLE
Error intitializing plugin with Interface

### ISSUE THREAD

**Issue by cheesasaurus** [decaprime/VampireCommandFramework#19]
When a plugin project has an Interface, this error is thrown while starting up the v rising server:

```
[Error  :Bloodstone] System.NullReferenceException: Object reference not set to an instance of an object.
   at VampireCommandFramework.CommandRegistry.IsGenericConverterContext(Type rootType)
   at VampireCommandFramework.CommandRegistry.RegisterConverter(Type converter)
   at VampireCommandFramework.CommandRegistry.RegisterAll(Assembly assembly)
   at VampireCommandFramework.CommandRegistry.RegisterAll()
   at VcfErrorExposure.Plugin.Load()
   at Bloodstone.Features.Reload.LoadPlugin(String path)
```

I created an example plugin to demonstrate the issue:
https://github.com/cheesasaurus/v-rising-vcf-error-demo

**Comment by decaprime** [comment]
Thanks for the great report @cheesasaurus. I'll hold off and encourage a PR as it looks like you already have a fork to fix this flaky check (which is equally flaky in `IsSpecificConverterContext`).
