### ISSUE TITLE
What is the reason for this error after the server is started?

### ISSUE THREAD

**Issue by tongren66** [decaprime/VampireCommandFramework#25]
[Warning:VampireCommandFramework] Hit unexpected exception executing command 鏀瑰悕
: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at KindredCommands.Commands.PlayerCommands.RenameMe(ChatCommandContext ctx, NewName newName)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at VampireCommandFramework.CommandRegistry.Handle(ICommandContext ctx, String input)

**Comment by decaprime** [comment]
This doesn't appear to be a VCF issue. This is an error that looks from inside KindredCommands, you should contact whoever authored the command `鏀瑰悕`
